# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
