# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='biditem',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Member'),
        ),
    ]
